language: php

env:
  - THENEEDFORTHIS=FAIL

matrix:
  include:
    - env: DBTYPE=mysql; MW=master; TYPE=coverage
      php: 5.3
    - env: DBTYPE=sqlite; MW=1.22.0
      php: 5.5
    - env: DBTYPE=mysql; MW=1.20.0
      php: 5.4

  exclude:
    - env: THENEEDFORTHIS=FAIL

script: bash ./build/travis/script.sh

after_success: bash ./build/travis/after_success.sh
