language: php

env:
  - THENEEDFORTHIS=FAIL

matrix:
  include:
    - env: DB=mysql; MW=master
      php: 5.6
    - env: DB=sqlite; MW=1.22.0
      php: 5.3
    - env: DB=mysql; MW=master
      php: hhvm
  exclude:
    - env: THENEEDFORTHIS=FAIL

install:
  - bash ./tests/travis/install-mediawiki.sh
  - bash ./tests/travis/install-semantic-watchlist.sh

script:
  - bash ./tests/travis/run-tests.sh

notifications:
  email:
    on_success: change
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#semantic-mediawiki"
    on_success: change
    on_failure: always
